spring:
  application:
    name: file
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB
server:
  port: 18003
  servlet:
    context-path: /file

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:9000/eureka/

file:
  path: F:file/
  domain: http://127.0.0.1:18000/file/static/




