spring:
  datasource:
    name: video
    url: jdbc:mysql://47.111.3.30:3306/video?useSSL=false&characterEncoding=utf-8&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: video
    password: Video@2020
  redis:
    host: 47.111.3.30
    port: 6379
    password: 311324

#  druid:
#    db-type: com.alibaba.druid.pool.DruidDataSource
#    # 初始化大小，最小，最大
#    initial-size: 5
#    min-idle: 5
#    max-active: 20
#    max-wait: 60000
#    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
#    time-between-eviction-runs-millis: 60000
#    # 配置一个连接在池中最小生存的时间，单位是毫秒
#    min-evictable-idle-time-millis: 300000
#    # 配置监控服务器
#    stat-view-servlet:
#      enabled: true
#      login-username: march
#      login-password: 311324
#      url-pattern: /druid/*
#logging:
#  level:
#    cn.marchawake.server.mapper: trace

#这里注意配置的名称
mybatis:
  mapper-locations: classpath:/mapper/**/*.xml



