spring:
  application:
    name: eurake

server:
  port: 9000

eureka:
  instance:
    #服务注册中心 IP 地址
    hostname: 47.111.3.30
  client:
    #是否检索服务
    fetch-registry: false
    #是否向服务注册中心注册自己
    register-with-eureka: false
    #服务注册中心的配置内容，指定服务注册中心的位置
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

